Repository gonzalespaulb/Pokemon-App, pull requests merged in 2021-07, with the labels that each got.

#12 remove boiler plate files
  pokeapp/src/App.css
  pokeapp/src/App.js
  pokeapp/src/logo.svg
Labels: documentation

#15 Pg 14 scss setup
  pokeapp/package-lock.json
  pokeapp/package.json
  pokeapp/src/App.js
  pokeapp/src/Brain.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_filterbar.scss
  pokeapp/src/styling/components/_navigation.scss
  pokeapp/src/styling/components/_pokemon-grid.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/main.scss
  pokeapp/src/styling/typography/_fonts.scss
  pokeapp/src/utilities/ApiCall.js
Labels: enhancement

#17 add the icons from the design
  pokeapp/src/Brain.js
  pokeapp/src/assets/bug.svg
  pokeapp/src/assets/close.svg
  pokeapp/src/assets/dark.svg
  pokeapp/src/assets/down-arrow.svg
  pokeapp/src/assets/dragon.svg
  pokeapp/src/assets/electric.svg
  pokeapp/src/assets/fairy.svg
  pokeapp/src/assets/fighting.svg
  pokeapp/src/assets/filter.svg
  pokeapp/src/assets/fire.svg
  pokeapp/src/assets/flying.svg
  pokeapp/src/assets/ghost.svg
  pokeapp/src/assets/grass.svg
  pokeapp/src/assets/ground.svg
  pokeapp/src/assets/ice.svg
  pokeapp/src/assets/menu.svg
  pokeapp/src/assets/normal.svg
  pokeapp/src/assets/poison.svg
  pokeapp/src/assets/psychic.svg
  pokeapp/src/assets/rock.svg
  pokeapp/src/assets/steel.svg
  pokeapp/src/assets/water.svg
Labels: enhancement

#21 add a filter feature
  pokeapp/package-lock.json
  pokeapp/src/Brain.js
  pokeapp/src/components/FilterBar.js
  pokeapp/src/utilities/ApiCall.js
Labels: documentation

#23 Sorting and Filtering
  pokeapp/src/Brain.js
  pokeapp/src/components/FilterBar.js
  pokeapp/src/styling/components/_filterbar.scss
  pokeapp/src/utilities/ApiCall.js
  pokeapp/src/utilities/enums.js
Labels: enhancement

#25 Js Wrapper Service Worker
  pokeapp/pokeapi-js-wrapper-sw.js
  pokeapp/src/App.js
  pokeapp/src/Brain.js
  pokeapp/src/index.js
Labels: enhancement

#30 PokeApi JS Wrapper Caching
  pokeapp/public/pokeapi-js-wrapper-sw.js
  pokeapp/src/utilities/ApiCall.js
Labels: bug, enhancement

#31 Initial styling to the navigation bar
  pokeapp/public/index.html
  pokeapp/src/components/Navigation.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_navigation.scss
Labels: enhancement

#33 Style landing page
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_filterbar.scss
  pokeapp/src/styling/components/_navigation.scss
  pokeapp/src/styling/components/_sidebar.scss
Labels: enhancement

#34 pokedex card render
  pokeapp/public/index.html
  pokeapp/src/Brain.js
  pokeapp/src/assets/bug.svg
  pokeapp/src/assets/dark.svg
  pokeapp/src/assets/dragon.svg
  pokeapp/src/assets/electric.svg
  pokeapp/src/assets/fairy.svg
  pokeapp/src/assets/fighting.svg
  pokeapp/src/assets/fire.svg
  pokeapp/src/assets/flying.svg
  pokeapp/src/assets/ghost.svg
  pokeapp/src/assets/grass.svg
  pokeapp/src/assets/ground.svg
  pokeapp/src/assets/ice.svg
  pokeapp/src/assets/normal.svg
  pokeapp/src/assets/poison.svg
  pokeapp/src/assets/psychic.svg
  pokeapp/src/assets/rock.svg
  pokeapp/src/assets/steel.svg
  pokeapp/src/assets/water.svg
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/ToolTip.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_tool-tip.scss
  pokeapp/src/styling/main.scss
  pokeapp/src/styling/typography/_fonts.scss
  pokeapp/src/utilities/pokemonIcon.js
Labels: enhancement

#36 replace margin values
  pokeapp/src/Brain.js
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_filterbar.scss
  pokeapp/src/styling/components/_navigation.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/layout/_main-container.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#38 Add key property
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/PokemonCard.js
Labels: bug

#40 Sidebar Info
  pokeapp/src/Brain.js
  pokeapp/src/assets/pokeDollar.svg
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
Labels: enhancement

#42 pokemon card grid restyled
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_pokemon-card.scss
  pokeapp/src/styling/main.scss
  pokeapp/src/utilities/ApiCall.js
Labels: bug

#44 Update Pokemon Height and Weight Units
  pokeapp/src/Brain.js
  pokeapp/src/components/Sidebar.js
Labels: enhancement

#48 Rendering mypoke
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
Labels: enhancement

#50 Update Pokedollars
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
Labels: enhancement

#52 Sell Pokemons
  pokeapp/src/components/PokemonCard.js
Labels: enhancement

#53 Initial game page
  pokeapp/src/Brain.js
  pokeapp/src/assets/slots.png
  pokeapp/src/assets/slots.svg
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/styling/layout/_main-container.scss
Labels: enhancement

#55 Pg 47 sidebar styling
  pokeapp/src/Brain.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_sidebar.scss
Labels: enhancement

#56 React Router Dom Setup
  pokeapp/package-lock.json
  pokeapp/package.json
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/Navigation.js
Labels: enhancement

#59 Activate Logic in Sidebar Buttons
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_sidebar.scss
Labels: enhancement

#61 Implement Redux
  pokeapp/package-lock.json
  pokeapp/package.json
  pokeapp/src/App.js
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/ToolTip.js
  pokeapp/src/redux/pokemonSlice.js
  pokeapp/src/redux/store.js
Labels: enhancement

#63 Sidebar Fix
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/Sidebar.js
Labels: bug

#65 Add Buy Sell Buttons to Cards
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/PokemonCard.js
Labels: enhancement

#66 Render pokemon gamepage
  pokeapp/src/Brain.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/styling/components/_pokemon-card.scss
  pokeapp/src/styling/components/gamepage.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#68 Stop Unwanted State Updates on Button Click
  pokeapp/src/components/PokemonCard.js
Labels: enhancement

#70 filter bar active state styling
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_filterbar.scss
Labels: enhancement

#71 Add Utility File and Move Functions to it
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/utilities/mappers.js
  pokeapp/src/utilities/pokemonIcon.js
Labels: enhancement

#73 Add images to use for the gamepage
  pokeapp/src/assets/pokemons/Mewtwo.png
  pokeapp/src/assets/pokemons/Pikachu.png
  pokeapp/src/assets/pokemons/areodactyl.png
  pokeapp/src/assets/pokemons/articuno.png
  pokeapp/src/assets/pokemons/bellsprouts.png
  pokeapp/src/assets/pokemons/bidoof.png
  pokeapp/src/assets/pokemons/bulbasaur.png
  pokeapp/src/assets/pokemons/char.png
  pokeapp/src/assets/pokemons/charizard.png
  pokeapp/src/assets/pokemons/charmander.png
  pokeapp/src/assets/pokemons/claydol.png
  pokeapp/src/assets/pokemons/diglett.png
  pokeapp/src/assets/pokemons/ditto.png
  pokeapp/src/assets/pokemons/dragonite.png
  pokeapp/src/assets/pokemons/dratini.png
  pokeapp/src/assets/pokemons/ekans.png
  pokeapp/src/assets/pokemons/evee.png
  pokeapp/src/assets/pokemons/flareon.png
  pokeapp/src/assets/pokemons/girafarig.png
  pokeapp/src/assets/pokemons/hoothoot.png
  pokeapp/src/assets/pokemons/jolteon.png
  pokeapp/src/assets/pokemons/kabuto.png
  pokeapp/src/assets/pokemons/kabutops.png
  pokeapp/src/assets/pokemons/ladyba.png
  pokeapp/src/assets/pokemons/lapras.png
  pokeapp/src/assets/pokemons/lickitung.png
  pokeapp/src/assets/pokemons/meowth.png
  pokeapp/src/assets/pokemons/mew.png
  pokeapp/src/assets/pokemons/misdreavus.png
  pokeapp/src/assets/pokemons/moltres.png
  pokeapp/src/assets/pokemons/mrmime1.png
  pokeapp/src/assets/pokemons/omanyte.png
  pokeapp/src/assets/pokemons/onix.png
  pokeapp/src/assets/pokemons/pancham.png
  pokeapp/src/assets/pokemons/piplup.png
  pokeapp/src/assets/pokemons/porygon.png
  pokeapp/src/assets/pokemons/psyduck.png
  pokeapp/src/assets/pokemons/sentret.png
  pokeapp/src/assets/pokemons/skitty.png
  pokeapp/src/assets/pokemons/slowpoke.png
  pokeapp/src/assets/pokemons/snorlax.png
  pokeapp/src/assets/pokemons/spiritomb.png
  pokeapp/src/assets/pokemons/squirtle.png
  pokeapp/src/assets/pokemons/tangela.png
  pokeapp/src/assets/pokemons/vaporeon.png
  pokeapp/src/assets/pokemons/voltorb.png
  pokeapp/src/assets/pokemons/weezing.png
  pokeapp/src/assets/pokemons/wobbuffet.png
  pokeapp/src/assets/pokemons/zangoose.png
  pokeapp/src/assets/pokemons/zaptos.png
Labels: enhancement

#76 Navigation Bug
  pokeapp/src/Brain.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_navigation.scss
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: bug, enhancement
