Repository gonzalespaulb/Pokemon-App, pull requests merged in 2021-08, with the labels that each got.

#83 Jd 2 sidebar search
  pokeapp/package-lock.json
  pokeapp/package.json
  pokeapp/src/Brain.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/index.css
  pokeapp/src/styling/components/_sidebar.scss
Labels: enhancement

#85 gamepage slot machine styling
  pokeapp/src/Brain.js
  pokeapp/src/assets/pokemons/aerodactyl.png
  pokeapp/src/assets/pokemons/bellsprout.png
  pokeapp/src/assets/pokemons/char.png
  pokeapp/src/assets/pokemons/eevee.png
  pokeapp/src/assets/pokemons/index.js
  pokeapp/src/assets/pokemons/ledyba.png
  pokeapp/src/assets/pokemons/mrmime.png
  pokeapp/src/assets/pokemons/zapdos.png
  pokeapp/src/assets/rollers/pikachu-roller.png
  pokeapp/src/assets/rollers/pokeball-roller.png
  pokeapp/src/components/GamePage.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_gamepage.scss
  pokeapp/src/styling/components/gamepage.scss
  pokeapp/src/styling/layout/_game-page-container.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#87 Connect the gamepage winnings to myPoke
  pokeapp/src/components/GamePage.js
  pokeapp/src/redux/pokemonSlice.js
  pokeapp/src/utilities/randomizer.js
Labels: enhancement

#89 enable scrolling in the won pokemon grid
  pokeapp/src/components/GamePage.js
  pokeapp/src/styling/components/_gamepage.scss
  pokeapp/src/styling/layout/_game-page-container.scss
Labels: enhancement

#92 Progress Bars and Badges (Part 1)
  pokeapp/package-lock.json
  pokeapp/package.json
  pokeapp/src/Brain.js
  pokeapp/src/components/BadgeSideBar.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/badges/Badge.js
  pokeapp/src/components/badges/BadgeSideBar.js
  pokeapp/src/components/badges/bagdeIcon.js
  pokeapp/src/redux/pokemonSlice.js
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/utilities/bagdeIcon.js
  pokeapp/src/utilities/pokemonIcon.js
Labels: enhancement

#95 Jd 94 searchbar bug
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_filterbar.scss
  pokeapp/src/styling/components/dist/_digital-card-binder.css
  pokeapp/src/styling/components/dist/_pokemon-card.css
  pokeapp/src/styling/components/dist/_sidebar.css
Labels: bug

#97 sidebar more information styling
  pokeapp/src/assets/indices/black-2.png
  pokeapp/src/assets/indices/black.jpeg
  pokeapp/src/assets/indices/blue.jpeg
  pokeapp/src/assets/indices/crystal.png
  pokeapp/src/assets/indices/diamond.jpeg
  pokeapp/src/assets/indices/emerald.jpeg
  pokeapp/src/assets/indices/firered.jpg
  pokeapp/src/assets/indices/gold.png
  pokeapp/src/assets/indices/heartgold.jpeg
  pokeapp/src/assets/indices/leafgreen.jpg
  pokeapp/src/assets/indices/pearl.jpeg
  pokeapp/src/assets/indices/platinum.jpg
  pokeapp/src/assets/indices/red.jpg
  pokeapp/src/assets/indices/ruby.jpeg
  pokeapp/src/assets/indices/sapphire.jpeg
  pokeapp/src/assets/indices/silver.png
  pokeapp/src/assets/indices/soulsilver.jpeg
  pokeapp/src/assets/indices/white-2.jpeg
  pokeapp/src/assets/indices/white.jpeg
  pokeapp/src/assets/indices/yellow.png
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/utilities/mappers.js
  pokeapp/src/utilities/pokemonGames.js
Labels: enhancement

#99 Kf 82 progress bar (Part 2)
  pokeapp/src/assets/badges/Toxic_Badge.png
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/badges/Badge.js
  pokeapp/src/components/badges/BadgeSideBar.js
  pokeapp/src/components/badges/bagdeIcon.js
  pokeapp/src/components/badges/utils/allTypesHelper.js
  pokeapp/src/redux/pokemonSlice.js
Labels: enhancement

#101 Update Filter-bar dropdown buttons styling
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/components/badges/bagdeIcon.js
  pokeapp/src/styling/components/_filterbar.scss
Labels: enhancement

#103 feat(scroll-bars):remove all scroll bars
  pokeapp/src/index.css
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#105 Update Images to a Better Quality
  pokeapp/src/Brain.js
Labels: enhancement

#108 Pokemon card buttons
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: enhancement

#109 Sidebar and Badge Sidebar Styling and Navigation
  pokeapp/src/Brain.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/badges/Badge.js
  pokeapp/src/components/badges/BadgeSideBar.js
  pokeapp/src/styling/components/_badge-sidebar.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#112 Fix Buying Bug
  pokeapp/src/redux/pokemonSlice.js
Labels: bug

#115 Cleaning Up Code
  pokeapp/src/Brain.js
  pokeapp/src/assets/pokemons/index.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/utilities/mappers.js
Labels: enhancement

#118 Stop more info from being rendered before it is supposed to
  pokeapp/src/components/Sidebar.js
Labels: bug

#120 feat(sidebar): add pokedollar icon to the pokemon value
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_pokemon-card.scss
  pokeapp/src/styling/components/_sidebar.scss
Labels: enhancement

#122 Pokemon cards box shadows
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: enhancement

#126 Sidebar update
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/SidebarNav.js
  pokeapp/src/components/badges/BadgeSideBar.js
  pokeapp/src/styling/components/_badge-sidebar.scss
Labels: enhancement

#129 slot machine effects
  pokeapp/src/assets/pokemons/index.js
  pokeapp/src/assets/pokemons/weezinggmax.png
  pokeapp/src/components/GamePage.js
  pokeapp/src/styling/components/_gamepage.scss
Labels: enhancement

#132 Add Click Handlers as Props and Organize Props
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/components/Layout.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/SidebarNav.js
  pokeapp/src/components/badges/BadgeSideBar.js
Labels: bug, enhancement

#134 Update Win Pokemon Reducer
  pokeapp/src/components/GamePage.js
  pokeapp/src/redux/pokemonSlice.js
Labels: enhancement

#138 Filter dropdown
  pokeapp/src/assets/uiIcons/filter.svg
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/styling/components/_filterbar.scss
Labels: enhancement

#136 Pg 131 slot machine click and reset
  pokeapp/src/components/GamePage.js
  pokeapp/src/styling/components/_gamepage.scss
Labels: enhancement

#140 fix bug on pokemon cards
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: bug

#142 Insufficient Funds
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/redux/pokemonSlice.js
  pokeapp/src/styling/components/_navigation.scss
Labels: enhancement

#143 Pokeball container
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/styling/colorschemes/_colors.scss
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: enhancement

#146 sidebar badges styling
  pokeapp/src/components/badges/Badge.js
  pokeapp/src/components/badges/BadgeSideBar.js
  pokeapp/src/components/badges/bagdeIcon.js
  pokeapp/src/styling/components/_badge-sidebar.scss
Labels: enhancement

#148 Kf 145 value change
  pokeapp/src/redux/pokemonSlice.js
Labels: enhancement

#149 Sidebar bugs
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: bug

#152 Add Omega Ruby Game
  pokeapp/src/assets/indices/omegaRuby.png
  pokeapp/src/components/Sidebar.js
  pokeapp/src/utilities/pokemonGames.js
Labels: bug

#159 Typeahead issues
  pokeapp/src/Brain.js
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_sidebar.scss
Labels: bug

#161 Add Toasts
  pokeapp/package-lock.json
  pokeapp/package.json
  pokeapp/src/Brain.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/badges/utils/allTypesHelper.js
  pokeapp/src/redux/pokemonSlice.js
  pokeapp/src/styling/main.scss
  pokeapp/src/utilities/toast.js
Labels: enhancement

#162 Pokemon Badges
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/badges/bagdeIcon.js
  pokeapp/src/redux/pokemonSlice.js
Labels: enhancement

#157 app wide font styling
  pokeapp/src/assets/uiIcons/filter.svg
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/components/Navigation.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/SidebarNav.js
  pokeapp/src/index.css
  pokeapp/src/styling/components/_badge-sidebar.scss
  pokeapp/src/styling/components/_filterbar.scss
  pokeapp/src/styling/components/_navigation.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/main.scss
  pokeapp/src/styling/typography/_fonts.scss
  pokeapp/src/utilities/mappers.js
Labels: enhancement

#165 Pg 158 sidebar animation
  pokeapp/src/Brain.js
  pokeapp/src/assets/uiIcons/close.svg
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/GamePage.js
  pokeapp/src/components/Layout.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/Sidebar.js
  pokeapp/src/components/badges/BadgeSideBar.js
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/layout/_main-container.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#168 Remove progress bar package
  pokeapp/package-lock.json
  pokeapp/package.json
Labels: enhancement

#171 bug(filter-dropdown): fix outside click on filter dropdown
  pokeapp/src/components/FilterBar.js
Labels: bug

#170 Pg 167 add logo
  pokeapp/src/assets/uiIcons/coingif.gif
  pokeapp/src/components/Navigation.js
  pokeapp/src/styling/components/_navigation.scss
Labels: enhancement

#173 Update Readme
  README.md
Labels: documentation

#174 Increment to version 1.0.0
  pokeapp/package.json
Labels: documentation

#185 fix the overlapping button on smaller devices
  pokeapp/src/styling/components/_sidebar.scss
Labels: bug

#186 MyPoke Empty State Placeholder
  pokeapp/.firebase/hosting.YnVpbGQ.cache
  pokeapp/.firebaserc
  pokeapp/firebase.json
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/styling/components/_digital-card-binder.scss
  pokeapp/src/styling/components/_my-poke.scss
  pokeapp/src/styling/main.scss
Labels: enhancement

#187 Quantity font size
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/styling/components/_pokemon-card.scss
Labels: bug

#188 Game Page Restyle
  pokeapp/src/styling/components/_gamepage.scss
Labels: enhancement

#189 fix the spacing issue when the percent is at 100
  pokeapp/src/styling/components/_badge-sidebar.scss
Labels: bug

#190 Jd 182 pokemon card hover
  pokeapp/src/components/PokemonCard.js
Labels: bug

#191 Search Bar Styling
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/main.scss
Labels: bug, enhancement

#194 Change Font Style and Color on MyPoke Page
  pokeapp/src/styling/components/_my-poke.scss
Labels: enhancement

#195 more information button background color
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/typography/_fonts.scss
Labels: bug

#197 Jd 192 badges buttons
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/SidebarNav.js
  pokeapp/src/styling/components/_badge-sidebar.scss
  pokeapp/src/styling/components/_sidebar.scss
  pokeapp/src/styling/typography/_fonts.scss
Labels: bug

#199 fix(sidebar): fix sidebar merge conflicts
  pokeapp/src/styling/components/_sidebar.scss
Labels: bug

#202 Sidebar pop up on mypoke and alphabetizing props
  pokeapp/src/components/DigitalCardBinder.js
  pokeapp/src/components/FilterBar.js
  pokeapp/src/components/FilterDropDown.js
  pokeapp/src/components/PokemonCard.js
  pokeapp/src/components/SidebarNav.js
Labels: bug

#203 Type Icon Color Fix
  pokeapp/src/assets/types/rock.svg
  pokeapp/src/assets/types/steel.svg
  pokeapp/src/styling/colorschemes/_colors.scss
Labels: bug

#205 replace the button color to base color
  pokeapp/src/assets/uiIcons/pokeDollar.svg
  pokeapp/src/styling/typography/_fonts.scss
Labels: bug

#208 Earn Coins Button
  pokeapp/src/components/Navigation.js
  pokeapp/src/styling/components/_navigation.scss
  pokeapp/src/styling/typography/_fonts.scss
Labels: enhancement

#211 Website title
  pokeapp/public/favicon.ico
  pokeapp/public/index.html
  pokeapp/public/pokecoin.gif
  pokeapp/src/assets/uiIcons/pokecoin.gif
Labels: bug

#212 Sidebar Quantity
  pokeapp/src/components/Sidebar.js
  pokeapp/src/styling/typography/_fonts.scss
Labels: enhancement

#214 feat(logo):add the final version of the logo
  pokeapp/src/components/Navigation.js
  pokeapp/src/styling/typography/_fonts.scss
Labels: enhancement

#215 update version to 1.0.1
  pokeapp/package.json
Labels: documentation
